local PREFABS = {
["shadowthrall_hands"] = true,
["shadowthrall_wings"] = true,
["shadowthrall_horns"] = true,
["voidcloth"] = true,
["voidcloth_scythe"] = true,
["voidclothhat"] = true,
["armor_voidcloth"] = true,
["voidcloth_umbrella"] = true,
["shadow_forge"] = true,
["fused_shadeling"] = true,
["fused_shadeling_bomb"] = true,

["lunarrift_portal"] = true,
["shadowrift_portal"] = true,
["lunarrift_crystal_big"] = true,

["spat"] = true,
["warg"] = true,
["stageusher"] = true,
["stagehand"] = true,
	
["scrapbook_page"] = true,

["smallghost"] = true,
	
["babybeefalo"] = true,
["beefalo"] = true,
["bat"] = true,
["bee"] = true,
["beeguard"] = true,
["bird_mutant"] = true,
["bird_mutant_spitter"] = true,
["bishop"] = true,
["birchnutdrake"] = true,
["bishop_nightmare"] = true,
["bunnyman"] = true,
["butterfly"] = true,
["buzzard"] = true,
["canary"] = true,
["carrat"] = true,
["cookiecutter"] = true,
["catcoon"] = true,
["crawlinghorror"] = true,
["crow"] = true,
["deer"] = true,
["deerclops"] = true,
--["deer_blue"] = true,
--["deer_red"] = true,
["dragonfly"] = true,
--["dropperweb"] = true,
["dustmoth"] = true,
["eyeplant"] = true,
["firehound"] = true,
["friendlyfruitfly"] = true,
["frog"] = true,
["fruitdragon"] = true,
["fruitfly"] = true,
["gestalt_guard"] = true,
["ghost"] = true,
["gnarwail"] = true,
["grassgator"] = true,
["grassgekko"] = true,
["hound"] = true,
["icehound"] = true,
["killerbee"] = true,
["knight"] = true,
["knight_nightmare"] = true,
["leif"] = true,
["lightcrab"] = true,
["lightflier"] = true,
["lightninggoat"] = true,
["lordfruitfly"] = true,
["lunarthrall_plant"] = true,
["lureplant"] = true,
["mandrake_active"] = true,
["merm"] = true,
["mermguard"] = true,
["mole"] = true,
["molebat"] = true,
["monkey"] = true,
["moonbutterfly"] = true,
["moose"] = true,
["mosquito"] = true,
["mossling"] = true,
["mushgnome"] = true,
["mutated_penguin"] = true,
["mutatedhound"] = true,
--["nightmarebeak"] = true,
["oceanhorror"] = true,
["oceanvine_cocoon"] = true,
["penguin"] = true,
["perd"] = true,
["pigguard"] = true,
["pigman"] = true,
["powder_monkey"] = true,
["prime_mate"] = true,
["puffin"] = true,
["rabbit"] = true,
["robin"] = true,
["robin_winter"] = true,
["rocky"] = true,
["rook"] = true,
["rook_nightmare"] = true,
["shark"] = true,
["slurper"] = true,
["slurtle"] = true,
["slurtlehole"] = true,
["smallbird"] = true,
["snurtle"] = true,
["spider"] = true,
["spider_dropper"] = true,
["spider_healer"] = true,
["spider_hider"] = true,
["spider_moon"] = true,
["spider_spitter"] = true,
["spider_warrior"] = true,
["spider_water"] = true,
["spiderqueen"] = true,
["squid"] = true,
["stalker"] = true,
["stalker_forest"] = true,
["stalker_atrium"] = true,
["tallbird"] = true,
["teenbird"] = true,
["tentacle"] = true,
["tentacle_pillar"] = true,
["tentacle_pillar_arm"] = true,
["terrorbeak"] = true,
["warglet"] = true,
["waterplant"] = true,
["wobster_moonglass_land"] = true,
["wobster_sheller_land"] = true,
["koalefant_summer"] = true,

["blueprint"]=true,
["halloweencandy_7"]=true,
["oceanfishingbobber_crow"]=true,
["winter_ornament_light2"]=true,
--["pepperpopper_spice_sugar"]=true,
--["honeyham_spice_chili"]=true,
--["glowberrymousse_spice_salt"]=true,
["wintersfeastfuel"]=true,
["boatpatch"]=true,
--["oceanfish_medium_5_inv"]=true,

--["messagebottle_throwable"]=true,
--["baconeggs_spice_garlic"]=true,

--["spear_lance"]=true,
--["quagmire_seedpacket"]=true,
["oceanfishinglure_hermit_heavy"]=true,
["drumstick_cooked"]=true,
["gunpowder"]=true,
["tacklesketch"]=true,
["dragontailhat"]=true,
--["wetgoop_spice_chili"]=true,
--["meatysalad_spice_garlic"]=true,
--["bananajuice_spice_sugar"]=true,
["milkywhites"]=true,
["shroom_skin"]=true,
["brush"]=true,
["pig_token"]=true,
--["yotb_beefalo_doll_beast"]=true,
--["quagmire_food_056"]=true,
--["barnaclepita_spice_sugar"]=true,
["halloweenpotion_bravery_small"]=true,
["stinger"]=true,
["koalefig_trunk"]=true,
["sketch"]=true,
["rock_avocado_fruit"]=true,
--["honeyham_spice_garlic"]=true,
--["quagmire_food_029"]=true,
--["potatotornado_spice_salt"]=true,
["chesspiece_guardianphase3"]=true,

--["fireballstaff"]=true,
["atrium_key"]=true,
["molehat"]=true,
["cave_banana"]=true,
["lobsterdinner"]=true,
["kabobs"]=true,

--["quagmire_food_038"]=true,

["slurtlehat"]=true,
--["quagmire_seedpacket"]=true,


["moonstorm_goggleshat"]=true,

--["lavaarena_healingflowerhat"]=true,
["lightbulb"]=true,

["earmuffshat"]=true,

["eel_cooked"]=true,
["hareball"]=true,
["pickaxe"]=true,
["chesspiece_carrat"]=true,
--["lavae_egg_cracked"]=true,
["powcake"]=true,
["chesspiece_guardianphase3"]=true,
["slingshot"]=true,
["baconeggs"]=true,
["salsa"]=true,
--["fishsticks_spice_chili"]=true,
--["carnivaldecor_figure_kit"]=true,
--["lobsterbisque_spice_garlic"]=true,

--["lavaarena_armormediumdamager"]=true,
--["californiaroll_spice_sugar"]=true,
["sketch"]=true,
--["quagmire_food_009"]=true,
--["quagmire_food_008"]=true,
["tentaclespots"]=true,

--["quagmire_food_061"]=true,
["sketch"]=true,
--["unagi_spice_chili"]=true,
["pepper_oversized"]=true,
--["quagmire_carrot"]=true,
--["lavaarena_healinggarlandhat"]=true,
--["honeyham_spice_sugar"]=true,
--["lavaarena_armor_hprecharger"]=true,
["turf_rocky"]=true,
["bedroll_furry"]=true,
["chesspiece_toadstool"]=true,
["catcoonhat"]=true,
["jellybean"]=true,
["moonbutterfly"]=true,
["hermit_pearl"]=true,
["oar_monkey"]=true,

["lutefisk"]=true,
["chesspiece_knight"]=true,
["portablecookpot_item"]=true,
--["potatotornado_spice_sugar"]=true,
--["frognewton_spice_chili"]=true,
["grass_umbrella"]=true,
["turf_mosaic_red"]=true,
--["barnaclesushi_spice_garlic"]=true,
["lucky_goldnugget"]=true,
--["onion_oversized_rotten"]=true,
["turf_monkey_ground"]=true,
--["bunnystew_spice_sugar"]=true,
["halloween_ornament_6"]=true,
["chesspiece_klaus"]=true,
["slingshotammo_gold"]=true,
["chesspiece_claywarg"]=true,
["balloonspeed"]=true,
--["leafymeatburger_spice_sugar"]=true,
["hotchili"]=true,
--["waffles_spice_chili"]=true,
["winter_ornament_plain2"]=true,
["chesspiece_kitcoon"]=true,
["opalpreciousgem"]=true,

--["pigtorch_fuel"]=true,
["slingshotammo_marble"]=true,
["asparagus_seeds"]=true,
--["barnaclestuffedfishhead_spice_garlic"]=true,
--["taffy_spice_salt"]=true,
["hammer"]=true,
["hermit_bundle"]=true,
["petals"]=true,
["balloons_empty"]=true,
--["shroomcake_spice_garlic"]=true,
["halloweencandy_14"]=true,
--["boat_magnet_kit"]=true,
--["taffy_spice_garlic"]=true,
--["carnivaldecor_lamp_kit"]=true,
--["mashedpotatoes_spice_salt"]=true,
["chum"]=true,
--["quagmire_food_017"]=true,
["lunarplanthat"]=true,

["treegrowthsolution"]=true,
--["moqueca_spice_garlic"]=true,
["dumbbell_marble"]=true,
--["trailmix_spice_chili"]=true,
["rock_avocado_fruit_ripe_cooked"]=true,
--["quagmire_food_045"]=true,

["costume_queen_body"]=true,

--["stuffedeggplant_spice_sugar"]=true,
--["californiaroll_spice_salt"]=true,
["halloween_ornament_3"]=true,
--["barnaclesushi_spice_chili"]=true,


["green_cap_cooked"]=true,
["sword_lunarplant"]=true,
--["beefalotreat_spice_sugar"]=true,
["spider_moon"]=true,
--["flowersalad_spice_chili"]=true,
["chesspiece_carrat"]=true,
--["honeyham_spice_salt"]=true,
--["quagmire_food_016"]=true,
--["watermelon_oversized_rotten"]=true,
--["bonesoup_spice_garlic"]=true,
--["jammypreserves_spice_garlic"]=true,
["wx78_moduleremover"]=true,
["orangestaff"]=true,
["potato_cooked"]=true,

--["barnaclesushi_spice_sugar"]=true,
["lucy"]=true,
["trinket_22"]=true,
["eggplant_seeds"]=true,
--["justeggs_spice_salt"]=true,
--["quagmire_food_025"]=true,
["mandrakesoup"]=true,

["book_bees"]=true,
["spiderhat"]=true,
["book_web"]=true,
--["oceanfish_small_4_inv"]=true,
--["beard_sack_3"]=true,

["blowdart_yellow"]=true,
--["ice_blueprint"]=true,
--["quagmire_seeds_7"]=true,
--["koalefig_trunk_spice_chili"]=true,

--["pumpkincookie_spice_sugar"]=true,
["bird_mutant_spitter"]=true,

["leafymeatsouffle"]=true,
--["lunar_forge_kit"]=true,
["chesspiece_manrabbit"]=true,
["sketch"]=true,
--["butterflymuffin_spice_chili"]=true,

--["surfnturf_spice_chili"]=true,
["chesspiece_clayhound"]=true,
["sketch"]=true,
--["justeggs_spice_garlic"]=true,


["chesspiece_anchor"]=true,
["chesspiece_minotaur"]=true,
--["quagmire_crabtrap"]=true,
--["quagmire_food_057"]=true,
["multitool_axe_pickaxe"]=true,
["antliontrinket"]=true,
["barnaclestuffedfishhead"]=true,
["nightmare_timepiece"]=true,
["oceanfishinglure_spinner_blue"]=true,
["trinket_8"]=true,
--["quagmire_coin1"]=true,
--["meatysalad_spice_sugar"]=true,
--["leafymeatsouffle_spice_sugar"]=true,
--["book_elemental"]=true,
--["quagmire_food_053"]=true,
--["hotchili_spice_salt"]=true,
["dragonfruit_oversized"]=true,
["chesspiece_butterfly"]=true,
--["lavaarena_armor_hpdamager"]=true,
["barnacle"]=true,
["antchovies"]=true,
["ratatouille"]=true,
--["dragonpie_spice_sugar"]=true,
["chesspiece_antlion"]=true,
["waxwelljournal"]=true,
["cookedmonstermeat"]=true,
["armorgrass"]=true,
["chesspiece_antlion"]=true,
["wereitem_moose"]=true,
["chesspiece_manrabbit"]=true,
["wateringcan"]=true,
["purplemooneye"]=true,
["winter_ornament_plain5"]=true,
--["monstertartare_spice_salt"]=true,
--["carnivalcannon_confetti_kit"]=true,
["trinket_39"]=true,

["ruinshat"]=true,
["torch"]=true,
["wormlight"]=true,
--["salsa_spice_salt"]=true,
["chesspiece_toadstool"]=true,
--["lavaarena_armor_hppetmastery"]=true,

--["butterflymuffin_spice_salt"]=true,
["monkey_smallhat"]=true,
--["lavaarena_armorextraheavy"]=true,
--["meatballs_spice_chili"]=true,
--["quagmire_turnip"]=true,
--["butterflymuffin_spice_sugar"]=true,
["bearger_fur"]=true,
["foliage"]=true,
--["quagmire_food_060"]=true,
["staff_tornado"]=true,
["compost"]=true,
["thulecite_pieces"]=true,
--["robot_blueprint"]=true,
["nutrientsgoggleshat"]=true,
--["yotb_beefalo_doll_formal"]=true,
["moon_tree_blossom"]=true,
--["yotr_fightring_kit"]=true,
--["quagmire_food_058"]=true,
["nitre"]=true,
["ruins_bat"]=true,
--["yotc_carrat_scale_item"]=true,
["chesspiece_formal"]=true,
["axe"]=true,
["batwing"]=true,
--["quagmire_food_003"]=true,
["batnose"]=true,
["durian_oversized"]=true,
["sewing_tape"]=true,
["ghostlyelixir_slowregen"]=true,
["beefalotreat"]=true,
["trinket_7"]=true,
--["quagmire_key_park"]=true,

["crow"]=true,
--["frogglebunwich_spice_chili"]=true,
["mutator_dropper"]=true,
["chesspiece_moosegoose"]=true,
["chesspiece_stalker"]=true,
["winter_ornament_boss_moose"]=true,
--["quagmire_sap"]=true,
--["kabobs_spice_garlic"]=true,
["tallbirdegg_cooked"]=true,
["potato_oversized"]=true,


["moonstorm_static_item"]=true,
--["figatoni_spice_garlic"]=true,
--["voltgoatjelly_spice_garlic"]=true,
--["quagmire_food_066"]=true,

--["lavaarena_armor_hpextraheavy"]=true,

--["humanmeat_cooked"]=true,
["sketch"]=true,

--["talleggs_spice_salt"]=true,

["backpack"]=true,

--["quagmire_plate_silver"]=true,
--["frogglebunwich_spice_garlic"]=true,
--["quagmire_food_047"]=true,
["fishmeat"]=true,
["carnival_vest_b"]=true,
["kelp"]=true,
--["seafoodgumbo_spice_chili"]=true,

["tacklesketch"]=true,
["winter_ornament_plain6"]=true,
["multiplayer_portal_moonrock_constr_plans"]=true,
["purplegem"]=true,

["froglegs_cooked"]=true,
--["handpillow_beefalowool"]=true,
--["barnaclinguine_spice_chili"]=true,
--["watermelonicle_spice_chili"]=true,
["shadowheart"]=true,
["papyrus"]=true,
["turf_fungus"]=true,
["waffles"]=true,
--["bonesoup_spice_sugar"]=true,
--["lobsterdinner_spice_chili"]=true,
["megaflare"]=true,
["armormarble"]=true,
--["humanmeat_dried"]=true,
["glowberrymousse"]=true,
["driftwood_log"]=true,

["ceviche"]=true,

["deer_antler1"]=true,
["boat_item"]=true,
["staff_lunarplant"]=true,
["trinket_34"]=true,
["monstermeat_dried"]=true,
["oceanfishingrod"]=true,
--["meatballs_spice_sugar"]=true,
--["taffy_spice_chili"]=true,
["flowerhat"]=true,

["flowersalad"]=true,
--["nightmarepie_spice_garlic"]=true,

["moonrockidol"]=true,
["diviningrod"]=true,
["sketch"]=true,
["gears"]=true,
--["carnivaldecor_plant_kit"]=true,
--["dragonpie_spice_salt"]=true,
["balloonparty"]=true,
["purebrilliance"]=true,
--["quagmire_food_059"]=true,
["fence_gate_item"]=true,
["horn"]=true,
["chesspiece_hornucopia"]=true,
["trinket_31"]=true,
["lunarplant_husk"]=true,
--["quagmire_sapbucket"]=true,
--["jellybean_spice_garlic"]=true,
["chesspiece_dragonfly"]=true,
["halloweenpotion_health_large"]=true,
["chesspiece_klaus"]=true,
["halloween_ornament_2"]=true,
--["asparagussoup_spice_garlic"]=true,
["mast_malbatross_item"]=true,
["stuffedeggplant"]=true,
["carnival_prizeticket"]=true,
["trinket_23"]=true,
["nightsword"]=true,
["chesspiece_eyeofterror"]=true,
["moonrockseed"]=true,
["cookingrecipecard"]=true,
["spear_wathgrithr"]=true,
--["onion_oversized_waxed"]=true,
["pocketwatch_heal"]=true,
--["watermelonicle_spice_sugar"]=true,
["eel"]=true,
--["barnaclinguine_spice_garlic"]=true,
["alterguardianhat"]=true,
["oceanfishinglure_spinner_green"]=true,
["pondfish"]=true,
["unagi"]=true,
--["yotr_food2"]=true,

--["ceviche_spice_salt"]=true,
["bunnystew"]=true,
--["quagmire_seedpacket"]=true,
--["powcake_spice_garlic"]=true,
--["taffy_spice_sugar"]=true,
["fishmeat_small_cooked"]=true,
--["quagmire_food_039"]=true,
--["quagmire_wheat"]=true,
["horrorfuel"]=true,
["chesspiece_anchor"]=true,
["battlesong_sanitygain"]=true,
--["trailmix_spice_sugar"]=true,
["costume_tree_body"]=true,
["chesspiece_dragonfly"]=true,
["chesspiece_catcoon"]=true,
["footballhat"]=true,

["mapscroll"]=true,
["goldenshovel"]=true,
--["quagmire_food_021"]=true,
--["lavaarena_armorheavy"]=true,
--["bodypillow_beefalowool"]=true,
--["oceanfishinglure_spoon_brown"]=true,
["roastturkey"]=true,
["wobster_sheller_dead_cooked"]=true,
["chesspiece_butterfly"]=true,
["sketch"]=true,
["dug_berrybush2"]=true,

--["bonestew_spice_garlic"]=true,
["winter_ornament_plain8"]=true,

["turf_road"]=true,
--["honeynuggets_spice_garlic"]=true,
["minifan"]=true,

--["quagmire_food_004"]=true,
--["yotc_seedpacket"]=true,
--["mandrakesoup_spice_salt"]=true,

["moon_altar_icon"]=true,

["honeyham"]=true,
["amulet"]=true,
["pomegranate"]=true,

--["leafloaf_spice_chili"]=true,
["pocketwatch_dismantler"]=true,
["tamales"]=true,
["marble"]=true,
--["potato_oversized_waxed"]=true,
--["fruitmedley_spice_sugar"]=true,
["mastupgrade_lamp_item"]=true,
["chesspiece_twinsofterror"]=true,
--["carnivaldecor_eggride4_kit"]=true,
--["potatotornado_spice_chili"]=true,
["playbill_the_doll"]=true,
["bonestew"]=true,
--["quagmire_food_022"]=true,
["abigail_flower"]=true,
--["potatotornado_spice_garlic"]=true,
["lightflier"]=true,
--["quagmire_pigeon"]=true,
["book_moon"]=true,
--["leafymeatburger_spice_chili"]=true,
["cookedmeat"]=true,


["sketch"]=true,
--["boat_bumper_shell_kit"]=true,
["turf_underrock"]=true,
--["bananajuice_spice_salt"]=true,
["portableblender_item"]=true,
--["watermelonicles"]=true,
--["quagmire_seedpacket"]=true,
--["oceanfish_medium_3_inv"]=true,
--["quagmire_food_bowl_goop"]=true,
--["boat_cannon_kit"]=true,


["leafloaf"]=true,
["tallbirdegg_cracked"]=true,
["winter_ornament_fancy8"]=true,
["malbatross_feathered_weave"]=true,

--["quagmire_salt_rack_item"]=true,

["cookedsmallmeat"]=true,
--["oceanfish_medium_7_inv"]=true,
["tacklesketch"]=true,
["book_temperature"]=true,
["kelphat"]=true,
["rock_avocado_fruit_ripe"]=true,
["plantregistryhat"]=true,

["fish"]=true,

["chesspiece_moon"]=true,
["minisign_drawn"]=true,
--["canary_poisoned"]=true,
--["lavaarena_rechargerhat"]=true,

["bugnet"]=true,
["chesspiece_moon"]=true,
--["frogglebunwich_spice_sugar"]=true,
["compass"]=true,
--["shroomcake_spice_chili"]=true,
["goatmilk"]=true,
["tacklesketch"]=true,
["mosquitosack"]=true,
["rope"]=true,
["hivehat"]=true,
["petals_evil"]=true,
--["quagmire_coin3"]=true,
["moon_altar_crown"]=true,
["spider_hider"]=true,
--["quagmire_food_049"]=true,
["spoiled_food"]=true,
["turf_fungus_red"]=true,
--["figatoni_spice_salt"]=true,
--["honeynuggets_spice_sugar"]=true,
["watermelonhat"]=true,
["mask_treehat"]=true,
["plantmeat"]=true,

["oar"]=true,
--["barnaclestuffedfishhead_spice_salt"]=true,
["ghostlyelixir_attack"]=true,
["chesspiece_carrat"]=true,
["book_light"]=true,

["cutlichen"]=true,

--["fruitmedley_spice_chili"]=true,
["compostwrap"]=true,

["chesspiece_crabking"]=true,
["turf_dragonfly"]=true,

--["quagmire_salmon"]=true,
--["durian_oversized_waxed"]=true,

["carrot_cooked"]=true,
["rainhat"]=true,
["chesspiece_manrabbit"]=true,
["houndwhistle"]=true,
["antlionhat"]=true,
["mask_queenhat"]=true,
["featherfan"]=true,
--["yotc_carrat_gym_direction_item"]=true,
["oceanfishinglure_spoon_blue"]=true,
--["pumpkincookie_spice_garlic"]=true,
["durian_seeds"]=true,
--["quagmire_food_bowl_burnt"]=true,
--["mandrakesoup_spice_garlic"]=true,
["teleportato_potato"]=true,
["dragonfruit"]=true,
["frogglebunwich"]=true,
["shroomcake"]=true,
["chesspiece_catcoon"]=true,
["winter_ornament_fancy7"]=true,
--["oceanfish_small_8_inv"]=true,
["dragonpie"]=true,
["raincoat"]=true,

--["frogfishbowl_spice_salt"]=true,
--["carrot_oversized_waxed"]=true,
["perdfan"]=true,
--["butterflymuffin_spice_garlic"]=true,
--["barnaclesushi_spice_salt"]=true,
["lureplantbulb"]=true,
--["quagmire_food_plate_goop"]=true,
--["yotc_carrat_race_checkpoint_item"]=true,
["reviver"]=true,
["soil_amender"]=true,
--["gazpacho_spice_chili"]=true,
["turf_meteor"]=true,
["greengem"]=true,
["blue_cap"]=true,
--["guacamole_spice_salt"]=true,
--["quagmire_food_024"]=true,
["scandata"]=true,
["deserthat"]=true,
["armordreadstone"]=true,


--["ceviche_spice_garlic"]=true,
["halloween_ornament_4"]=true,
["chesspiece_rook"]=true,
["fossil_piece"]=true,
--["veggieomlet_spice_sugar"]=true,
--["handpillow_petals"]=true,
["sketch"]=true,
["turf_ruinstiles_glow"]=true,
--["barnaclepita_spice_salt"]=true,
["wagstaff_tool_4"]=true,
--["unagi_spice_garlic"]=true,

["mulleddrink"]=true,
--["surfnturf_spice_garlic"]=true,
--["yotr_decor_2_item"]=true,
["winter_ornament_plain9"]=true,
["halloweenpotion_sparks"]=true,

["pocketwatch_warp"]=true,
["firepen"]=true,
--["barnaclinguine_spice_sugar"]=true,
["gazpacho"]=true,
["wagstaff_tool_3"]=true,


--["bonesoup_spice_chili"]=true,
["reskin_tool"]=true,
["bernie_active"]=true,

--["quagmire_food_043"]=true,
--["jellybean_spice_sugar"]=true,
["monstertartare"]=true,
["lavae_cocoon"]=true,
--["hammer_mjolnir"]=true,
["wx78module_maxhealth"]=true,
["halloweenpotion_embers"]=true,
["shovel_lunarplant"]=true,
["cactus_meat_cooked"]=true,

["halloween_ornament_1"]=true,
["monsterlasagna"]=true,
["moon_cap_cooked"]=true,
["oceanfishingbobber_ball"]=true,
["trinket_43"]=true,
["pigskin"]=true,
["fireflies"]=true,
["turf_ruinsbrick"]=true,
["sketch"]=true,
--["monstertartare_spice_garlic"]=true,
["pocket_scale"]=true,
--["bunnystew_spice_salt"]=true,
--["quagmire_food_019"]=true,

--["lavaarena_lucy"]=true,

--["carnival_plaza_kit"]=true,
["deerclops_eyeball"]=true,
--["carnivaldecor_eggride1_kit"]=true,

["winter_food5"]=true,

--["bodypillow_steelwool"]=true,
["winter_ornament_boss_deerclops"]=true,
["garlic"]=true,
--["asparagussoup_spice_chili"]=true,
["dug_sapling_moon"]=true,
["durian"]=true,
["dug_trap_starfish"]=true,
--["oceanfish_small_5_inv"]=true,
["battlesong_instant_taunt"]=true,
["lavae_egg"]=true,
["beardhair"]=true,
["wx78module_maxsanity"]=true,
["watermelon_cooked"]=true,
["cactus_flower"]=true,

--["quagmire_onion"]=true,
["transistor"]=true,
["bundlewrap"]=true,
["barnaclinguine"]=true,
["singingshell_octave3"]=true,
["mask_dollhat"]=true,

["battlesong_durability"]=true,
--["voltgoatjelly_spice_salt"]=true,
--["icecream_spice_garlic"]=true,
--["carnivaldecor_banner_kit"]=true,



["blueamulet"]=true,
--["lavaarena_armormedium"]=true,
["chesspiece_beequeen"]=true,
["chesspiece_pipe"]=true,
["eggplant"]=true,
--["dragonpie_spice_chili"]=true,
--["honeynuggets_spice_salt"]=true,
["feather_robin"]=true,
["onion_oversized"]=true,
["meatballs"]=true,
["turf_grass"]=true,
--["nature_blueprint"]=true,
["bird_egg"]=true,
["halloweencandy_5"]=true,
["turf_carpetfloor2"]=true,
["moon_altar_glass"]=true,
--["turkeydinner_spice_sugar"]=true,
["armor_bramble"]=true,
["plantmeat_cooked"]=true,
--["bonestew_spice_salt"]=true,
["turf_ruinstrim"]=true,
["glasscutter"]=true,

--["quagmire_pot_small"]=true,
--["surfnturf_spice_sugar"]=true,
--["lavaarena_lightdamagerhat"]=true,
["spider_healer_item"]=true,


["flint"]=true,
--["kabobs_spice_sugar"]=true,
["moonstorm_spark"]=true,
["fence_item"]=true,
["armor_sanity"]=true,


["seeds"]=true,

["green_mushroomhat"]=true,
--["ceviche_spice_chili"]=true,

--["mashedpotatoes_spice_garlic"]=true,
["carrat"]=true,
["pumpkin_cooked"]=true,

["trinket_44"]=true,

["winterhat"]=true,
--["oceanfish_small_6_inv"]=true,

--["quagmire_food_013"]=true,
--["bonesoup_spice_salt"]=true,
["winter_ornament_boss_eyeofterror2"]=true,
["butter"]=true,
["winter_ornament_festivalevents2"]=true,

--["bodypillow_petals"]=true,
["fence_rotator"]=true,
["turkeydinner"]=true,

--["carnival_seedpacket"]=true,
["winter_ornament_boss_celestialchampion4"]=true,
["sculpture_rooknose"]=true,


["battlesong_healthgain"]=true,
["chesspiece_hornucopia"]=true,
["bird_egg_cooked"]=true,
["moonglass"]=true,
["smallmeat"]=true,
--["sweettea_spice_garlic"]=true,
--["quagmire_food_014"]=true,
--["yotb_beefalo_doll_doll"]=true,
["tourtiere"]=true,

--["lobsterdinner_spice_garlic"]=true,
["dragonheadhat"]=true,
--["quagmire_pot_syrup"]=true,
["greenamulet"]=true,
["wereitem_beaver"]=true,
--["quagmire_food_006"]=true,
--["war_blueprint"]=true,
--["quagmire_food_051"]=true,
["glassspike_short"]=true,
--["quagmire_salmon_cooked"]=true,

--["quagmire_seedpacket"]=true,
--["hotchili_spice_sugar"]=true,
["wathgrithrhat"]=true,

["blue_mushroomhat"]=true,
--["quagmire_pebblecrab"]=true,
--["talleggs_spice_garlic"]=true,
--["carnivalgame_wheelspin_kit"]=true,
["birdtrap"]=true,
--["quagmire_seedpacket"]=true,
["kitcoon_nametag"]=true,
["trinket_20"]=true,
["chesspiece_muse"]=true,
--["waffles_spice_salt"]=true,

["oceanfishingbobber_robin"]=true,
--["surfnturf_spice_salt"]=true,
--["potatosouffle_spice_salt"]=true,
["winter_ornament_boss_antlion"]=true,
--["kitcoondecor1_kit"]=true,
--["quagmire_coin2"]=true,
["sketch"]=true,
["panflute"]=true,

["battlesong_instant_panic"]=true,
--["figkabab_spice_sugar"]=true,
--["fruitmedley_spice_garlic"]=true,
--["icecream_spice_chili"]=true,
["chesspiece_klaus"]=true,
["sketch"]=true,
--["yotb_pattern_fragment_2"]=true,
["perogies"]=true,
["moonrocknugget"]=true,

["giftwrap"]=true,
--["beefalofeed_spice_chili"]=true,
--["nightmarepie_spice_chili"]=true,
--["ratatouille_spice_sugar"]=true,
["gravy"]=true,
["mermhat"]=true,
["coontail"]=true,
["refined_dust"]=true,
["oceanfishinglure_spoon_green"]=true,

--["salsa_spice_chili"]=true,
["chesspiece_minotaur"]=true,
["turf_pebblebeach"]=true,

["polishcookie"]=true,
["eggplant_cooked"]=true,
["carnival_vest_a"]=true,
--["frozenbananadaiquiri_spice_salt"]=true,
["klaussackkey"]=true,
["honeycomb"]=true,
--["bananajuice_spice_garlic"]=true,
["spore_small"]=true,
["trinket_45"]=true,
--["asparagus_oversized_rotten"]=true,
["leafymeatburger"]=true,

--["salsa_spice_sugar"]=true,
["blue_cap_cooked"]=true,
--["quagmire_casseroledish"]=true,


["armorwood"]=true,
["premiumwateringcan"]=true,
["spider_repellent"]=true,
["meatysalad"]=true,
["latkes"]=true,

["turf_savanna"]=true,
--["quagmire_slaughtertool"]=true,


["dug_marsh_bush"]=true,
--["quagmire_food_050"]=true,
--["dragonchilisalad_spice_garlic"]=true,
["onion_cooked"]=true,

--["quagmire_pot"]=true,
--["redpouch_yotr"]=true,
--["frogfishbowl_spice_chili"]=true,



--["oceanfishinglure_spoon_silver"]=true,

--["baconeggs_spice_chili"]=true,
["wx78module_maxhealth2"]=true,

["chesspiece_malbatross"]=true,

["surfnturf"]=true,
["winter_ornament_light3"]=true,
["boat_grass_item"]=true,
["beargervest"]=true,

--["powcake_spice_chili"]=true,
["anchor_item"]=true,
--["yotb_stage_item"]=true,
["pickaxe_lunarplant"]=true,
["teleportato_ring"]=true,
["winter_ornament_fancy5"]=true,
["book_rain"]=true,
--["jammypreserves_spice_sugar"]=true,
["frozenbananadaiquiri"]=true,
["potatosouffle"]=true,
--["lavaarena_eyecirclethat"]=true,
["sketch"]=true,
--["frozenbananadaiquiri_spice_chili"]=true,
--["blowdart_lava"]=true,
["trinket_11"]=true,
--["yotc_carrat_race_start_item"]=true,
--["turkeydinner_spice_salt"]=true,
["winter_ornament_light5"]=true,
["chesspiece_kitcoon"]=true,
["lobsterbisque"]=true,
["chesspiece_eyeofterror"]=true,
--["veggieomlet_spice_salt"]=true,
["spice_garlic"]=true,
--["vegstinger_spice_garlic"]=true,
["trinket_40"]=true,
["krampus_sack"]=true,
["krampus"] = true,
["mutator_warrior"]=true,
["cutstone"]=true,
["gift"]=true,
["winter_ornament_boss_noeyered"]=true,

["trunk_cooked"]=true,

["book_sleep"]=true,
--["lobsterdinner_spice_sugar"]=true,
["tillweed"]=true,

["pumpkinpie"]=true,

--["californiaroll_spice_garlic"]=true,
--["fishtacos_spice_chili"]=true,
--["carnivaldecor_figure_kit_season2"]=true,

["dragonbodyhat"]=true,
["rabbit"]=true,
["smallmeat_dried"]=true,
--["leafymeatsouffle_spice_garlic"]=true,
["frogfishbowl"]=true,
["barnaclesushi"]=true,
--["quagmire_cookedsmallmeat"]=true,

--["seafoodgumbo_spice_salt"]=true,
--["jammypreserves_spice_salt"]=true,
["battlesong_sanityaura"]=true,
--["pumpkincookie_spice_chili"]=true,

--["perogies_spice_sugar"]=true,
--["vegstinger_spice_salt"]=true,
["bernie_inactive"]=true,

["asparagus"]=true,
["cavein_boulder"]=true,
["fishmeat_small"]=true,
["pepperpopper"]=true,
["oceanfishingbobber_robin_winter"]=true,
["onion_seeds"]=true,
["minisign_item"]=true,
["poop"]=true,

--["monsterlasagna_spice_salt"]=true,
["waterplant_bomb"]=true,
--["justeggs_spice_chili"]=true,


--["unagi_spice_salt"]=true,

["halloweenpotion_moon"]=true,

["hutch_fishbowl"]=true,
["mask_dollrepairedhat"]=true,
--["nightmarepie_spice_sugar"]=true,
--["stuffedeggplant_spice_chili"]=true,
["farm_plow_item"]=true,
--["yotb_beefalo_doll_festive"]=true,

["halloweencandy_12"]=true,
--["glowberrymousse_spice_sugar"]=true,
--["quagmire_food_041"]=true,
["chesspiece_muse"]=true,
--["quagmire_food_036"]=true,
["nightmarefuel"]=true,
["wagstaff_tool_2"]=true,
["trinket_38"]=true,
--["wetgoop_spice_sugar"]=true,
["rocks"]=true,
["chesspiece_beefalo"]=true,

["pinecone"]=true,


["firenettles"]=true,
["oceanfishingbobber_goose"]=true,
--["pepperpopper_spice_salt"]=true,
--["sweettea_spice_sugar"]=true,
["halloweenpotion_sanity_small"]=true,
["glommerflower"]=true,
--["glowberrymousse_spice_garlic"]=true,


["dock_kit"]=true,
["robin"]=true,
["watermelon_oversized"]=true,
["miniboatlantern"]=true,
--["lobsterdinner_spice_salt"]=true,
["freshfruitcrepes"]=true,
["sketch"]=true,
["chesspiece_beequeen"]=true,
["boat_magnet_beacon"]=true,
--["salsa_spice_garlic"]=true,
--["yotp_food1"]=true,
--["carnivaldecor_eggride3_kit"]=true,
--["oceanfish_small_1_inv"]=true,

--["quagmire_food_026"]=true,
["turf_fungus_green"]=true,

["sketch"]=true,
["guano"]=true,
--["seafoodgumbo_spice_garlic"]=true,
["sketch"]=true,
["monkey_mediumhat"]=true,
--["baconeggs_spice_salt"]=true,
["feather_robin_winter"]=true,
["chesspiece_bishop"]=true,
["watermelon_seeds"]=true,
--["meatballs_spice_salt"]=true,

--["quagmire_food_048"]=true,
["chesspiece_clayhound"]=true,
--["figkabab_spice_chili"]=true,
["moqueca"]=true,

--["monstertartare_spice_sugar"]=true,
["dug_sapling"]=true,
["bananapop"]=true,
--["figatoni_spice_chili"]=true,
["eyebrellahat"]=true,
["puffin"]=true,
["trinket_17"]=true,
--["quagmire_mushrooms"]=true,
["wall_moonrock_item"]=true,
["fishingrod"]=true,
--["yotr_token"]=true,
["singingshell_octave5"]=true,
--["yotr_food4"]=true,
--["yotr_food3"]=true,
--["yotr_food1"]=true,
["bushhat"]=true,
["chesspiece_stalker"]=true,
--["boat_bumper_kelp_kit"]=true,
["trinket_12"]=true,
["sweetpotato"]=true,
--["yotr_decor_1_item"]=true,
--["yotp_food2"]=true,
["chesspiece_knight"]=true,
--["perogies_spice_garlic"]=true,
--["monstertartare_spice_chili"]=true,
--["shroomcake_spice_sugar"]=true,
["redmooneye"]=true,
--["yotc_carrat_race_finish_item"]=true,
--["lavaarena_firebomb"]=true,
["wagstaff_tool_5"]=true,
--["quagmire_garlic"]=true,
["beefalohat"]=true,
--["yotb_sewingmachine_item"]=true,

--["glowberrymousse_spice_chili"]=true,
["moonglass_charged"]=true,
["boomerang"]=true,
["chesspiece_rook"]=true,
["wx78_scanner_item"]=true,
--["kabobs_spice_salt"]=true,
--["yotb_pattern_fragment_3"]=true,
--["yotb_pattern_fragment_1"]=true,

["turf_archive"]=true,
--["frognewton_spice_sugar"]=true,
--["festive_blueprint"]=true,

--["doll_blueprint"]=true,
--["beast_blueprint"]=true,

--["quagmire_food_031"]=true,
--["yotc_carrat_gym_reaction_item"]=true,
["red_mushroomhat"]=true,
--["yotb_beefalo_doll_robot"]=true,
["winter_ornament_boss_krampus"]=true,
--["yotb_beefalo_doll_nature"]=true,
--["yotb_beefalo_doll_war"]=true,
--["yotb_post_item"]=true,
["wx78module_bee"]=true,
["sewing_kit"]=true,
["frognewton"]=true,
["asparagussoup"]=true,
["monstermeat"]=true,
["wx78module_light"]=true,
["wx78module_taser"]=true,
["wx78module_cold"]=true,
["wx78module_nightvision"]=true,
--["wetgoop_spice_salt"]=true,
["book_silviculture"]=true,
["minerhat"]=true,
["wx78module_movespeed2"]=true,
["chesspiece_malbatross"]=true,
["blowdart_pipe"]=true,
--["wall_stone_2_item"]=true,

--["leafymeatsouffle_spice_chili"]=true,
["wortox_soul"]=true,

--["koalefig_trunk_spice_garlic"]=true,
["dug_bananabush"]=true,
["wormlight_lesser"]=true,

--["unagi_spice_sugar"]=true,
["chesspiece_crabking"]=true,
--["moqueca_spice_salt"]=true,
["wobster_sheller_dead"]=true,
["wobster_moonglass_land"]=true,
--["icecream_spice_sugar"]=true,
["firestaff"]=true,
["pitchfork"]=true,
--["asparagussoup_spice_salt"]=true,
["winter_ornament_festivalevents5"]=true,
--["gazpacho_spice_garlic"]=true,
["winter_ornament_plain7"]=true,
--["quagmire_food_068"]=true,
["golden_farm_hoe"]=true,
--["quagmire_crate"]=true,
["spider_water"]=true,
["watermelonicle"]=true,
["winter_food6"]=true,
["winter_food4"]=true,
["winter_food3"]=true,
["winter_food2"]=true,
["winter_food1"]=true,

["stuffing"]=true,
["chesspiece_formal"]=true,
["bibingka"]=true,
["berrysauce"]=true,
["pickledherring"]=true,
["onemanband"]=true,
["cabbagerolls"]=true,
["festivefish"]=true,
--["gazpacho_spice_sugar"]=true,
--["quagmire_book_shadow"]=true,
--["quagmire_crate"]=true,
--["quagmire_seedpacket"]=true,
["winter_ornament_boss_wagstaff"]=true,
["winter_ornament_boss_eyeofterror1"]=true,

["voltgoatjelly"]=true,
["winter_ornament_boss_celestialchampion3"]=true,
--["ratatouille_spice_garlic"]=true,
["winter_ornament_boss_celestialchampion2"]=true,
["chesspiece_pipe"]=true,
--["quagmire_potato_cooked"]=true,
["blowdart_sleep"]=true,
["honeynuggets"]=true,
["winter_ornament_boss_hermithouse"]=true,
["winter_ornament_boss_toadstool_misery"]=true,

["winter_ornament_boss_minotaur"]=true,
--["quagmire_food_035"]=true,
["winter_ornament_boss_crabkingpearl"]=true,
["chesspiece_beefalo"]=true,
["winter_ornament_boss_toadstool"]=true,
["winter_ornament_boss_noeyeblue"]=true,
["halloweencandy_13"]=true,
["winter_ornament_boss_fuelweaver"]=true,
["saddle_race"]=true,
["mastupgrade_lightningrod_item"]=true,
["winter_ornament_boss_dragonfly"]=true,
["winter_ornament_boss_beequeen"]=true,
["winter_ornament_boss_bearger"]=true,
["armordragonfly"]=true,
["wobster_sheller_land"]=true,
["fruitflyfruit"]=true,
["winter_ornament_festivalevents4"]=true,
--["figkabab_spice_salt"]=true,
["winter_ornament_light7"]=true,
["mask_foolhat"]=true,
--["glassspike_med"]=true,
["winter_ornament_fancy6"]=true,
["winter_ornament_fancy4"]=true,
["icehat"]=true,
["winter_ornament_fancy2"]=true,
["winter_ornament_fancy1"]=true,
["winter_ornament_plain12"]=true,
["thurible"]=true,

["winter_ornament_plain10"]=true,
["winter_ornament_plain4"]=true,
["winter_ornament_plain3"]=true,

["winter_ornament_plain1"]=true,
--["lavaarena_crowndamagerhat"]=true,
["moon_tree_blossom"]=true,
["whip"]=true,
--["quagmire_pot_hanger_item"]=true,
["wereitem_goose"]=true,
["kelp_cooked"]=true,
--["quagmire_seeds_2"]=true,
["winter_food8"]=true,
["spice_chili"]=true,
["moonbutterflywings"]=true,
["messagebottle"]=true,
["nightcaphat"]=true,
--["turkeydinner_spice_chili"]=true,
["chesspiece_hornucopia"]=true,
["feather_crow"]=true,

--["quagmire_turnip_cooked"]=true,
--["carnivalgame_memory_kit"]=true,
["alterguardianhatshard"]=true,

["waterballoon"]=true,
--["healingstaff"]=true,
["waterplant_planter"]=true,

["rock_avocado_fruit_sprout"]=true,
["sketch"]=true,
["dreadstonehat"]=true,
--["talleggs_spice_sugar"]=true,
["meat"]=true,


["trinket_28"]=true,
["terrarium"]=true,
["walrus_tusk"]=true,
--["quagmire_saltrock"]=true,
["lifeinjector"]=true,

--["wall_ruins_2_item"]=true,
["beefalo_groomer_item"]=true,
["wall_ruins_item"]=true,
["tacklesketch"]=true,
--["kitcoondecor2_kit"]=true,
["cutless"]=true,
["yellowmooneye"]=true,
["wall_wood_item"]=true,
["halloweencandy_2"]=true,


["wagstaff_tool_1"]=true,
--["beefalotreat_spice_chili"]=true,
["berries_cooked"]=true,
["berries"]=true,
--["potato_oversized_rotten"]=true,
["potato_seeds"]=true,
["palmcone_seed"]=true,
["fishtacos"]=true,
["cactus_meat"]=true,

["watermelon"]=true,
--["quagmire_food_067"]=true,


["moon_altar_seed"]=true,
--["watermelon_oversized_waxed"]=true,
["kelp_dried"]=true,
--["carnivalcannon_streamer_kit"]=true,
--["leafymeatburger_spice_garlic"]=true,
["berries_juicy_cooked"]=true,
["berries_juicy"]=true,
["asparagus_cooked"]=true,
["butterfly"]=true,
["carrot_oversized"]=true,
["carrot_seeds"]=true,
--["quagmire_bowl_silver"]=true,
["pomegranate_cooked"]=true,

["bee"]=true,
["pomegranate_oversized"]=true,
["onion"]=true,
["corn_cooked"]=true,
["slingshotammo_slow"]=true,


["corn"]=true,
--["corn_oversized_rotten"]=true,
--["potatosouffle_spice_chili"]=true,
--["corn_oversized_waxed"]=true,
["corn_oversized"]=true,
["corn_seeds"]=true,
["durian_cooked"]=true,
--["durian_oversized_rotten"]=true,

--["eggplant_oversized_waxed"]=true,
--["quagmire_tomato"]=true,
["pepper_cooked"]=true,
["pepper"]=true,
["chesspiece_formal"]=true,
--["pepper_oversized_waxed"]=true,
["pepper_seeds"]=true,
--["pumpkin_oversized_waxed"]=true,
["pumpkin_seeds"]=true,
["dragonfruit_cooked"]=true,
["telestaff"]=true,
["dreadstone"]=true,
["figatoni"]=true,
["dragonfruit_seeds"]=true,
["tomato_cooked"]=true,
["tomato"]=true,
["trinket_24"]=true,
--["tomato_oversized_rotten"]=true,
--["tomato_oversized_waxed"]=true,
["tomato_oversized"]=true,
["tomato_seeds"]=true,
["shovel"]=true,
["garlic_cooked"]=true,
--["garlic_oversized_waxed"]=true,
["garlic_oversized"]=true,

["garlic_seeds"]=true,
["fig_cooked"]=true,
["fig"]=true,
["umbrella"]=true,
["winter_ornament_festivalevents1"]=true,
["chesspiece_formal"]=true,
["spider_healer"]=true,
["turf_shellbeach"]=true,
["turf_mosaic_blue"]=true,

["vegstinger"]=true,
--["redpouch_yotb"]=true,

["moon_altar_ward"]=true,
["eyemaskhat"]=true,

["turf_ruinstiles"]=true,
["turf_ruinsbrick_glow"]=true,
["turf_mud"]=true,
--["frogfishbowl_spice_garlic"]=true,
["turf_sinkhole"]=true,
["turf_cave"]=true,
["chesspiece_moosegoose"]=true,
["turf_carpetfloor"]=true,
["turf_woodfloor"]=true,

["turf_forest"]=true,
--["oceanfishinglure_spinner_yellow"]=true,
["trinket_26"]=true,
["trunkvest_winter"]=true,
["trunkvest_summer"]=true,
["trunk_winter"]=true,
["trunk_summer"]=true,
["trinket_46"]=true,
--["monsterlasagna_spice_garlic"]=true,
["trinket_41"]=true,
["trinket_37"]=true,
--["pepperpopper_spice_garlic"]=true,
["trinket_36"]=true,
["dragonchilisalad"]=true,
["trinket_35"]=true,
["trinket_33"]=true,
["trinket_30"]=true,
["trinket_29"]=true,
["royal_jelly"]=true,
["slurper_pelt"]=true,
["trinket_25"]=true,
["trinket_21"]=true,
["trinket_18"]=true,
["trinket_14"]=true,
["trinket_13"]=true,
["trinket_9"]=true,
["trinket_6"]=true,
--["beard_sack_2"]=true,
["trinket_4"]=true,
["trinket_3"]=true,
["trinket_2"]=true,
--["justeggs_spice_sugar"]=true,
["mutator_spitter"]=true,
["trident"]=true,
["sunkenchest"]=true,
["winter_ornament_boss_crabking"]=true,
--["fishsticks_spice_sugar"]=true,
["chesspiece_bearger"]=true,
--["lavaarena_tiaraflowerpetalshat"]=true,
--["guacamole_spice_garlic"]=true,
["trap"]=true,
["book_horticulture"]=true,
["livingtree_root"]=true,
["shieldofterror"]=true,
["lighter"]=true,
["cutreeds"]=true,
["costume_mirror_body"]=true,
["twigs"]=true,
["sketch"]=true,
--["yotc_carrat_gym_stamina_item"]=true,
["fish_cooked"]=true,
--["ratatouille_spice_chili"]=true,
--["quagmire_food_020"]=true,
["tillweedsalve"]=true,
--["pepper_oversized_rotten"]=true,
["chesspiece_clayhound"]=true,
["bullkelp_root"]=true,
--["leafymeatburger_spice_salt"]=true,
["thulecite"]=true,

["tentaclespike"]=true,
--["quagmire_food_052"]=true,
--["moqueca_spice_sugar"]=true,
["teleportato_crank"]=true,
--["jellybean_spice_salt"]=true,
["winter_ornament_light4"]=true,
["tallbirdegg"]=true,
["tacklesketch"]=true,
["sketch"]=true,
["tacklesketch"]=true,
["wall_hay_item"]=true,
["tacklesketch"]=true,
["tacklesketch"]=true,
["tacklesketch"]=true,
["tacklesketch"]=true,
["batnose_cooked"]=true,
["tacklesketch"]=true,
--["lavaarena_strongdamagerhat"]=true,
["chesspiece_crabking"]=true,
--["lobsterbisque_spice_sugar"]=true,
["manrabbit_tail"]=true,
["chesspiece_twinsofterror"]=true,

["chesspiece_antlion"]=true,
["tacklecontainer"]=true,
["sweatervest"]=true,
["moon_cap"]=true,
["purpleamulet"]=true,
["firecrackers"]=true,
["succulent_picked"]=true,
["balloon"]=true,
--["yotc_seedpacket_rare"]=true,
["steeringwheel_item"]=true,
["steelwool"]=true,
["figkabab"]=true,
["pumpkincookie"]=true,
--["beefalofeed_spice_sugar"]=true,
["orangemooneye"]=true,
["stash_map"]=true,


["chesspiece_knight"]=true,
["mashedpotatoes"]=true,
--["barnaclepita_spice_garlic"]=true,
--["beefalofeed_spice_garlic"]=true,
--["frogfishbowl_spice_sugar"]=true,
--["quagmire_spotspice_sprig"]=true,
["chesspiece_stalker"]=true,
["book_research_station"]=true,
--["lobsterbisque_spice_salt"]=true,
["portabletent_item"]=true,
["opalstaff"]=true,
["chesspiece_malbatross"]=true,
["yellowstaff"]=true,
["greenstaff"]=true,
--["dragonfruit_oversized_rotten"]=true,
["icestaff"]=true,
--["lavaarena_armorlight"]=true,
--["carnivaldecor_eggride2_kit"]=true,

["spoiled_fish"]=true,
["chesspiece_bishop"]=true,
["spidereggsack"]=true,
["spiderden_bedazzler"]=true,
["mutator_water"]=true,
--["jellybean_spice_chili"]=true,
["mutator_moon"]=true,
["trinket_1"]=true,
["trinket_19"]=true,
["slurper"]=true,
["winter_food9"]=true,
["spider_dropper"]=true,
["rottenegg"]=true,
["spider"]=true,
--["lavaarena_armorlightspeed"]=true,
["spice_salt"]=true,
["costume_doll_body"]=true,
["spice_sugar"]=true,
["spicepack"]=true,
--["nightmarepie_spice_salt"]=true,
["pondeel"]=true,
--["oceanfish_small_3_inv"]=true,
["soil_amender_fermented"]=true,
--["quagmire_seeds_1"]=true,
["skeletonhat"]=true,
["potatotornado"]=true,
["slurtle_shellpieces"]=true,
--["carnival_prizebooth_kit"]=true,
["moon_altar_idol"]=true,
["trinket_27"]=true,
["slingshotammo_poop"]=true,
["mutator_hider"]=true,
--["beard_sack_1"]=true,
["mole"]=true,
["slingshotammo_rock"]=true,
["sleepbomb"]=true,
["potatosack"]=true,
["halloweencandy_9"]=true,
--["quagmire_food_055"]=true,

--["quagmire_food_001"]=true,
["dug_berrybush_juicy"]=true,
--["quagmire_sap_spoiled"]=true,
--["figatoni_spice_sugar"]=true,
["chesspiece_claywarg"]=true,
--["bananajuice_spice_chili"]=true,
["portablespicer_item"]=true,
--["perogies_spice_chili"]=true,
--["humanmeat"]=true,
--["quagmire_food_063"]=true,
--["flowersalad_spice_sugar"]=true,
--["oceanfish_small_9_inv"]=true,
["balloonhat"]=true,
["chesspiece_twinsofterror"]=true,
["chesspiece_malbatross"]=true,

["seedpouch"]=true,
--["oceanfishinglure_spoon_yellow"]=true,
["sketch"]=true,
["deer_antler1"]=true,
--["blowdart_lava2"]=true,
["pumpkin"]=true,
--["quagmire_casseroledish_small"]=true,
["sculpture_bishophead"]=true,
["chesspiece_moosegoose"]=true,
["twiggy_nut"]=true,
["chesspiece_manrabbit"]=true,
["honey"]=true,
--["quagmire_grill_small_item"]=true,
["chesspiece_minotaur"]=true,
["slingshotammo_thulecite"]=true,
--["kabobs_spice_chili"]=true,
["bathbomb"]=true,
--["fishtacos_spice_salt"]=true,

["justeggs"]=true,
--["koalefig_trunk_spice_sugar"]=true,
["cave_banana_cooked"]=true,
["heatrock"]=true,
["boards"]=true,
["lightninggoathorn"]=true,
["turf_beard_rug"]=true,
--["ceviche_spice_sugar"]=true,
["chesspiece_dragonfly"]=true,
["cookiecutterhat"]=true,
--["bananapop_spice_sugar"]=true,
--["quagmire_food_044"]=true,
--["fishtacos_spice_garlic"]=true,

["blackflag"]=true,
--["yotp_food3"]=true,

--["glassspike_tall"]=true,
--["oceanfish_medium_6_inv"]=true,

["trinket_15"]=true,
--["freshfruitcrepes_spice_sugar"]=true,
["waxpaper"]=true,
--["victorian_blueprint"]=true,

["armorslurper"]=true,
["book_light_upgraded"]=true,

["bonesoup"]=true,
--["bodypillow_kelp"]=true,
--["powcake_spice_sugar"]=true,

["sketch"]=true,
--["monsterlasagna_spice_chili"]=true,
["miniflare"]=true,
--["mandrakesoup_spice_sugar"]=true,
--["lavaarena_armormediumrecharger"]=true,
["hawaiianshirt"]=true,
["canary"]=true,
--["quagmire_food_042"]=true,
["sketch"]=true,
--["hotchili_spice_garlic"]=true,
["chesspiece_deerclops"]=true,
--["lobsterbisque_spice_chili"]=true,
--["stuffedeggplant_spice_garlic"]=true,
["chesspiece_muse"]=true,
["wx78module_maxhunger"]=true,
--["mandrakesoup_spice_chili"]=true,
["fossil_piece"]=true,
["turf_mosaic_grey"]=true,

--["quagmire_seeds_3"]=true,
--["oceanfish_medium_1_inv"]=true,
["walrushat"]=true,
--["sweettea_spice_chili"]=true,
["carnival_gametoken"]=true,
--["frognewton_spice_garlic"]=true,
--["bullkelp_beachedroot"]=true,
["wall_stone_item"]=true,
["winter_ornament_boss_klaus"]=true,
--["garlic_oversized_rotten"]=true,
["malbatross_beak"]=true,
--["quagmire_book_fertilizer"]=true,

["greenmooneye"]=true,
["book_tentacles"]=true,
["ash"]=true,
--["bonestew_spice_chili"]=true,
["archive_resonator_item"]=true,

--["watermelonicle_spice_salt"]=true,
["chesspiece_rook"]=true,
--["quagmire_crate"]=true,

["wx78module_maxhunger1"]=true,
["froglegs"]=true,
--["redpouch_yotp"]=true,


["mandrake"]=true,
["cutgrass"]=true,
["winter_ornament_light6"]=true,

--["frozenbananadaiquiri_spice_garlic"]=true,
["beef_bell"]=true,
["panettone"]=true,
["chesspiece_toadstool"]=true,

--["quagmire_crabmeat"]=true,
["beemine"]=true,


--["oceanfish_small_2_inv"]=true,
--["moqueca_spice_chili"]=true,
--["quagmire_foliage_cooked"]=true,
["hambat"]=true,
--["quagmire_smallmeat"]=true,
["redgem"]=true,
["winter_ornament_light1"]=true,
["bedroll_straw"]=true,
--["dragonchilisalad_spice_chili"]=true,
["book_fish"]=true,
["halloweencandy_6"]=true,
--["trailmix_spice_garlic"]=true,





["winter_ornament_boss_celestialchampion1"]=true,
["pocketwatch_portal"]=true,
--["jammypreserves_spice_chili"]=true,
--["quagmire_garlic_cooked"]=true,
["pocketwatch_recall"]=true,
--["carnivalgame_herding_kit"]=true,
--["quagmire_key"]=true,
--["oceanfish_medium_4_inv"]=true,
["nightstick"]=true,
["ghostlyelixir_speed"]=true,


["slingshotammo_freeze"]=true,
["ghostflower"]=true,
["fertilizer"]=true,
["dug_rock_avocado_bush"]=true,

["lantern"]=true,
--["oceanfish_medium_2_inv"]=true,

["boneshard"]=true,
--["quagmire_seedpacket"]=true,
["guacamole"]=true,
--["carnivalgame_feedchicks_kit"]=true,
["chesspiece_deerclops"]=true,
["charcoal"]=true,
["crumbs"]=true,

--["bananapop_spice_salt"]=true,

["wx78module_movespeed"]=true,
--["vegstinger_spice_sugar"]=true,
["bandage"]=true,
["wx78module_maxsanity1"]=true,
["oar_driftwood"]=true,
["sketch"]=true,
--["quagmire_crabmeat_cooked"]=true,
--["quagmire_burnt_ingredients"]=true,
--["quagmire_spotspice_ground"]=true,
--["quagmire_food_069"]=true,
--["koalefig_trunk_spice_salt"]=true,
["carnival_vest_c"]=true,
["red_cap_cooked"]=true,
--["quagmire_food_015"]=true,
["chesspiece_beequeen"]=true,
--["bunnystew_spice_chili"]=true,
--["lavaarena_heavyblade"]=true,
["halloweencandy_10"]=true,
["chesspiece_dragonfly"]=true,
["barnaclepita"]=true,

["turf_checkerfloor"]=true,
["winter_ornament_festivalevents3"]=true,

["reflectivevest"]=true,

["costume_king_body"]=true,

--["barnaclestuffedfishhead_spice_chili"]=true,
["cattoy_mouse"]=true,
--["bunnystew_spice_garlic"]=true,
--["quagmire_food_007"]=true,

["oceanfishinglure_spinner_red"]=true,
--["pomegranate_oversized_waxed"]=true,
["goggleshat"]=true,

--["veggieomlet_spice_garlic"]=true,


--["book_fossil"]=true,
["green_cap"]=true,
["yellowamulet"]=true,
["sketch"]=true,
["mast_item"]=true,
["ghostlyelixir_shield"]=true,
["spider_spitter"]=true,
--["eggplant_oversized_rotten"]=true,

["chesspiece_crabking"]=true,
["trinket_16"]=true,

["feather_canary"]=true,
["chesspiece_anchor"]=true,

["californiaroll"]=true,
["chesspiece_knight"]=true,
--["quagmire_food_028"]=true,

--["pumpkin_oversized_rotten"]=true,
--["quagmire_potato"]=true,

["butterflymuffin"]=true,
--["shroomcake_spice_salt"]=true,
--["healingsalve"]=true,
["trinket_42"]=true,
["moonrockcrater"]=true,

["chesspiece_minotaur"]=true,
--["potatosouffle_spice_garlic"]=true,
["piggyback"]=true,

["chesspiece_beefalo"]=true,
["chesspiece_pawn"]=true,
["lavae_tooth"]=true,
["bomb_lunarplant"]=true,
["dumbbell_golden"]=true,
["halloweenpotion_sanity_large"]=true,
--["quagmire_food_034"]=true,
["winter_ornament_boss_malbatross"]=true,
["potato"]=true,
--["quagmire_food_032"]=true,
--["meatysalad_spice_salt"]=true,
["teleportato_box"]=true,
["chesspiece_claywarg"]=true,
["carnivalfood_corntea"]=true,
["chesspiece_pawn"]=true,
["bluegem"]=true,

["minotaurhorn"]=true,
["minotaur"]=true,

["glassblock"]=true,
--["carnivalcannon_sparkle_kit"]=true,
--["californiaroll_spice_chili"]=true,

["taffy"]=true,
--["mashedpotatoes_spice_chili"]=true,
--["quagmire_syrup"]=true,
["dustmeringue"]=true,
--["leafloaf_spice_sugar"]=true,
--["fishtacos_spice_sugar"]=true,
--["handpillow_kelp"]=true,
["chesspiece_pipe"]=true,


["sweettea"]=true,

["saddle_war"]=true,
["oceanfishinglure_hermit_rain"]=true,
["drumstick"]=true,

["halloweencandy_11"]=true,

["orangegem"]=true,
["oceantreenut"]=true,
["featherpencil"]=true,
["messagebottleempty"]=true,
--["quagmire_food_005"]=true,

--["gazpacho_spice_salt"]=true,

--["pumpkincookie_spice_salt"]=true,
["costume_blacksmith_body"]=true,
--["carnivalgame_puckdrop_kit"]=true,
["hermit_cracked_pearl"]=true,
--["quagmire_seedpacket"]=true,


["chesspiece_butterfly"]=true,
["costume_fool_body"]=true,
["sketch"]=true,
--["quagmire_food_064"]=true,
["orangeamulet"]=true,
["sketch"]=true,
["sketch"]=true,
["chesspiece_antlion"]=true,
["goldenaxe"]=true,
["sketch"]=true,
--["freshfruitcrepes_spice_garlic"]=true,
["halloweenpotion_health_small"]=true,

--["asparagussoup_spice_sugar"]=true,

["sketch"]=true,
["sketch"]=true,
--["quagmire_flour"]=true,
["singingshell_octave4"]=true,
["deer_antler2"]=true,
["trap_bramble"]=true,

["shell_cluster"]=true,

["icepack"]=true,
--["oceanfishableflotsam"]=true,
["chesspiece_eyeofterror"]=true,
["armorsnurtleshell"]=true,
["turf_ruinstrim_glow"]=true,
["carrot"]=true,
["redlantern"]=true,
["winter_ornament_plain11"]=true,
--["quagmire_seeds_6"]=true,


--["veggieomlet_spice_chili"]=true,
--["frozenbananadaiquiri_spice_sugar"]=true,
["asparagus_oversized"]=true,
--["quagmire_food_011"]=true,
["seeds_cooked"]=true,
["nightmarepie"]=true,
--["redpouch_yot_catcoon"]=true,
["turf_deciduous"]=true,
["spore_tall"]=true,
["butterflywings"]=true,
["saddle_basic"]=true,
["armorruins"]=true,
["batbat"]=true,
["ice"]=true,
--["oceanfishinglure_spinner_orange"]=true,
--["asparagus_oversized_waxed"]=true,
["supertacklecontainer"]=true,


["sketch"]=true,
["bird_mutant"]=true,
["sculpture_knighthead"]=true,
["spider_whistle"]=true,
--["quagmire_hoe"]=true,
["chesspiece_kitcoon"]=true,

--["quagmire_food_010"]=true,
--["quagmire_onion_cooked"]=true,
["spear"]=true,

--["carnivalgame_shooting_kit"]=true,
--["boat_rotator_kit"]=true,
["saltrock"]=true,
--["bananapop_spice_chili"]=true,
["glommerwings"]=true,
["dragon_scales"]=true,
["halloweencandy_8"]=true,

["farm_hoe"]=true,
["saddlehorn"]=true,
["chesspiece_beefalo"]=true,

["log"]=true,
["trinket_32"]=true,
--["hotchili_spice_chili"]=true,
--["waffles_spice_sugar"]=true,
["fruitmedley"]=true,
["walterhat"]=true,
["spore_medium"]=true,
["tophat"]=true,
--["yotb_beefalo_doll_ice"]=true,
--["spear_gungnir"]=true,
--["quagmire_crate"]=true,
--["voltgoatjelly_spice_chili"]=true,
["chesspiece_twinsofterror"]=true,

--["figkabab_spice_garlic"]=true,

["chesspiece_claywarg"]=true,
--["quagmire_food_033"]=true,
["jammypreserves"]=true,
["bluemooneye"]=true,
["oceanfishinglure_spoon_red"]=true,
["goose_feather"]=true,
["chesspiece_pawn"]=true,
["oceanfishinglure_hermit_drowsy"]=true,
["fishingnet"]=true,
--["beefalotreat_spice_garlic"]=true,
["moonglassaxe"]=true,
["silk"]=true,
["pomegranate_seeds"]=true,
--["dragonchilisalad_spice_salt"]=true,
["barnacle_cooked"]=true,
["houndstooth"]=true,

["razor"]=true,
["blowdart_fire"]=true,
["oceanfishingbobber_oval"]=true,
["armor_lunarplant"]=true,
--["quagmire_food_030"]=true,
--["yotc_carrat_gym_speed_item"]=true,

--["oceanfish_medium_8_inv"]=true,
["chesspiece_bishop"]=true,
["goldenpickaxe"]=true,
["halloweencandy_3"]=true,
["chesspiece_moon"]=true,
["cookedmandrake"]=true,
["spoiled_fish_small"]=true,
--["potatosouffle_spice_sugar"]=true,
--["quagmire_salt"]=true,
["cursed_monkey_token"]=true,
--["vegstinger_spice_chili"]=true,


["chesspiece_catcoon"]=true,

--["quagmire_portal_key"]=true,
["halloween_ornament_5"]=true,

["chesspiece_hornucopia"]=true,

["book_fire"]=true,
--["quagmire_seeds_4"]=true,
["chesspiece_anchor"]=true,
["winter_food7"]=true,
["winter_ornament_boss_pearl"]=true,
--["quagmire_tomato_cooked"]=true,
["eggplant_oversized"]=true,
["bundle"]=true,
--["guacamole_spice_sugar"]=true,
--["pomegranate_oversized_rotten"]=true,
--["quagmire_carrot_cooked"]=true,
["book_birds"]=true,
--["quagmire_oven_item"]=true,
["acorn"]=true,

--["frogglebunwich_spice_salt"]=true,
--["redpouch"]=true,
["wetpouch"]=true,
["chesspiece_eyeofterror"]=true,
--["quagmire_mushrooms_cooked"]=true,
["mosquito"]=true,
["winter_ornament_light8"]=true,
["book_gardening"]=true,

["archive_lockbox"]=true,
--["quagmire_grill_item"]=true,
--["quagmire_goatmilk"]=true,
["cannonball_rock_item"]=true,

--["quagmire_food_065"]=true,

["chesspiece_klaus"]=true,
["goldenpitchfork"]=true,

--["quagmire_food_054"]=true,
--["quagmire_food_046"]=true,
["red_cap"]=true,
["cookbook"]=true,

--["quagmire_food_037"]=true,
--["fishsticks_spice_garlic"]=true,
["halloweencandy_4"]=true,
["battlesong_fireresistance"]=true,
--["quagmire_food_027"]=true,
--["quagmire_food_023"]=true,

["dumbbell_gem"]=true,
--["handpillow_steelwool"]=true,

--["quagmire_food_012"]=true,
--["guacamole_spice_chili"]=true,
--["formal_blueprint"]=true,
["robin_winter"]=true,
--["quagmire_food_040"]=true,
--["quagmire_food_plate_burnt"]=true,
--["oceanfish_medium_9_inv"]=true,
--["mashedpotatoes_spice_sugar"]=true,
["strawhat"]=true,
["chesspiece_deerclops"]=true,
["forgetmelots"]=true,
["tacklesketch"]=true,
--["meatballs_spice_garlic"]=true,
["chesspiece_carrat"]=true,
--["quagmire_crate"]=true,
["beeswax"]=true,
["fishsticks"]=true,
["bananajuice"]=true,
["dumbbell"]=true,
--["baconeggs_spice_sugar"]=true,

["eyeturret_item"]=true,
--["wetgoop_spice_garlic"]=true,
--["pumpkin_lantern"]=true,
["goldnugget"]=true,
["propsign"]=true,
["chesspiece_bishop"]=true,
["chester_eyebone"]=true,
--["quagmire_food_062"]=true,
--["carrot_oversized_rotten"]=true,

["armorskeleton"]=true,
--["frognewton_spice_salt"]=true,
--["freshfruitcrepes_spice_chili"]=true,
--["ratatouille_spice_salt"]=true,
["mutator_healer"]=true,
["furtuft"]=true,

["talleggs"]=true,
["pavlova"]=true,
--["seafoodgumbo_spice_sugar"]=true,

["oceanfishingbobber_malbatross"]=true,
--["beefalofeed_spice_salt"]=true,
--["flowersalad_spice_garlic"]=true,
--["meatysalad_spice_chili"]=true,
["halloweenpotion_bravery_large"]=true,
["pig_coin"]=true,

--["stuffedeggplant_spice_salt"]=true,
--["leafloaf_spice_salt"]=true,
--["oceanfish_small_7_inv"]=true,
["livinglog"]=true,
--["fishsticks_spice_salt"]=true,
--["sweettea_spice_salt"]=true,
--["waffles_spice_garlic"]=true,
--["trailmix_spice_salt"]=true,

--["honeynuggets_spice_chili"]=true,
["chesspiece_moon"]=true,
["chesspiece_toadstool"]=true,

["deer_antler3"]=true,
["book_horticulture_upgraded"]=true,
--["perogies_spice_salt"]=true,


--["barnaclepita_spice_chili"]=true,
--["powcake_spice_salt"]=true,
["chesspiece_guardianphase3"]=true,
--["voltgoatjelly_spice_sugar"]=true,
--["icecream_spice_salt"]=true,
["wetgoop"]=true,
--["flowersalad_spice_salt"]=true,
["meat_dried"]=true,
["cookiecuttershell"]=true,


["glommerfuel"]=true,
--["leafymeatsouffle_spice_salt"]=true,
--["dragonpie_spice_garlic"]=true,
--["fruitmedley_spice_salt"]=true,
--["monsterlasagna_spice_sugar"]=true,


--["barnaclestuffedfishhead_spice_sugar"]=true,

--["beefalotreat_spice_salt"]=true,
["beefalowool"]=true,
--["blowdart_walrus"]=true,
--["yotb_beefalo_doll_victorian"]=true,
["gnarwail_horn"]=true,
["trinket_5"]=true,
--["leafloaf_spice_garlic"]=true,
--["turkeydinner_spice_garlic"]=true,
["mask_blacksmithhat"]=true,
["carnivalgame_feedchicks_food"]=true,
["beefalofeed"]=true,
--["freshfruitcrepes_spice_salt"]=true,
["trailmix"]=true,
["candybag"]=true,
--["dragonfruit_oversized_waxed"]=true,
["veggieomlet"]=true,


["chesspiece_muse"]=true,
["icecream"]=true,
["turf_desertdirt"]=true,
["chesspiece_rook"]=true,
["wx78module_music"]=true,
["mask_mirrorhat"]=true,
["pocketwatch_weapon"]=true,
--["dragonchilisalad_spice_sugar"]=true,
["mask_kinghat"]=true,
["pocketwatch_parts"]=true,
["wx78module_heat"]=true,
["dug_monkeytail"]=true,
["dug_grass"]=true,
--["redpouch_yotc"]=true,

["dug_berrybush"]=true,
["slurtleslime"]=true,
["yellowgem"]=true,
["townportaltalisman"]=true,
["polly_rogershat"]=true,

["pocketwatch_revive"]=true,
["dock_woodposts_item"]=true,
["pumpkin_oversized"]=true,
["phlegm"]=true,
["palmcone_scale"]=true,
["featherhat"]=true,
["turf_fungus_moon"]=true,
["trinket_10"]=true,
["mask_dollbrokenhat"]=true,
--["bonestew_spice_sugar"]=true,
["oceanfishinglure_hermit_snow"]=true,
--["oceanfishinglure_spinner_white"]=true,
["chesspiece_deerclops"]=true,
["killerbee"]=true,
["oceanfishingbobber_canary"]=true,
["ghostlyelixir_fastregen"]=true,
["chesspiece_butterfly"]=true,
["turf_marsh"]=true,




["acorn_cooked"]=true,
--["barnaclinguine_spice_salt"]=true,
--["ocean_trawler_kit"]=true,

["chesspiece_pipe"]=true,

["chesspiece_moosegoose"]=true,
["halloweencandy_1"]=true,
["chesspiece_beequeen"]=true,
["fishmeat_cooked"]=true,
["batwing_cooked"]=true,
--["bananapop_spice_garlic"]=true,
--["quagmire_seeds_5"]=true,
["ghostlyelixir_retaliation"]=true,
["winter_ornament_fancy3"]=true,
--["lavaarena_feathercrownhat"]=true,

["marblebean"]=true,


["malbatross_feather"]=true,
["spidergland"]=true,
["trap_teeth"]=true,

--["quagmire_food_018"]=true,
["lightcrab"]=true,
["chesspiece_guardianphase3"]=true,
--["kitcoonden_kit"]=true,
["balloonvest"]=true,


["book_brimstone"]=true,
--["quagmire_food_002"]=true,
["chesspiece_clayhound"]=true,
["batnosehat"]=true,
["chesspiece_catcoon"]=true,
["beehat"]=true,

["spider_warrior"]=true,
--["talleggs_spice_chili"]=true,
["chesspiece_pawn"]=true,
["chesspiece_kitcoon"]=true,

["seafoodgumbo"]=true,
--["pepperpopper_spice_chili"]=true,
["cane"]=true,

["alterguardian_phase1"]=true,
["crabking"]=true,
["toadstool"]=true,
["glommer"]=true,
["malbatross"]=true,
["walrus"] = true,
["little_walrus"] = true,









["acorn_sapling"]=true,
["adventure_portal"]=true,
["alterguardian_contained"]=true,
["anchor"]=true,
["ancient_altar"]=true,
["animal_track"]=true,
--["antchovies_group"]=true,
["antlion"]=true,
["antlion_sinkhole"]=true,
["archive_centipede_husk"]=true,
["archive_cookpot"]=true,
["archive_lockbox_dispencer"]=true,
["archive_moon_statue"]=true,
--["archive_orchestrina"]=true,
--["archive_pillar"]=true,  -- DONT NEED?
["archive_portal"]=true,
["archive_resonator"]=true,
["archive_rune_statue"]=true,
["archive_security_desk"]=true,
["archive_switch"]=true,
--["arrowsign"]=true,
--["atrium_fence"]=true, -- TODO
["atrium_gate"]=true,
["atrium_idol"]=true,
--["atrium_key_icon"]=true,
["atrium_light"]=true,
["atrium_overgrowth"]=true,
["atrium_rubble"]=true,
["atrium_statue"]=true,
["bananabush"]=true,
["basalt"]=true,
["basalt_pillar"]=true,
["batcave"]=true,
["beebox"]=true,
["beebox_hermit"]=true,
["beefalo_groomer"]=true,
["beehive"]=true,
--["beemine_maxwell"]=true,
["beequeenhive"]=true,
["berrybush"]=true,
["berrybush_juicy"]=true,
["berrybush2"]=true,
--["bigshadowtentacle"]=true,
["birdcage"]=true,
["blue_mushroom"]=true,
["boat"]=true,
["boat_bumper_kelp"]=true,
["boat_bumper_shell"]=true,
["boat_cannon"]=true,
["boat_grass"]=true,
["boat_magnet"]=true,
["boat_pirate"]=true,
--["Boatfragment"]=true,
["bookstation"]=true,
--["brokentool"]=true,
--["bullkelp"]=true,
["cactus"]=true,
["campfire"]=true,
["carrat_planted"]=true,
["carrot_planted"]=true,
["cartographydesk"]=true,
["catcoonden"]=true,
["cave_banana_tree"]=true,
["cave_entrance"]=true,
["cave_entrance_ruins"]=true,
["cave_exit"]=true,
["cave_fern"]=true,
--["cave_hole"]=true,
["charlie_lecturn"]=true,
--["charlie_seat"]=true,
--["charlie_stage"]=true,  - POI
["chessjunk"]=true,
["coldfire"]=true,
["coldfirepit"]=true,
["compostingbin"]=true,
["cookpot"]=true,
["critterlab"]=true,
["daywalker_pillar"]=true,
--["daywalker_pillar_hole"]=true, --POI
["dead_sea_bones"]=true,
["deciduoustree_tall"]=true,
["dirtpile"]=true,
["diviningrodbase"]=true,
["dock_woodposts"]=true,
["dragonflychest"]=true,
["dragonflyfurnace"]=true,
--["driftwood"]=true,
--["dummytarget"]=true,
--["dummytarget_lunar"]=true,
--["dummytarget_shadow"]=true,
["dustmothden"]=true,
["endtable"]=true,
["evergreen_tall"]=true,
["eyeturret"]=true,
["farm_plant_asparagus"]=true,
["farm_plant_carrot"]=true,
["farm_plant_corn"]=true,
["farm_plant_dragonfruit"]=true,
["farm_plant_durian"]=true,
["farm_plant_eggplant"]=true,
["farm_plant_garlic"]=true,
["farm_plant_onion"]=true,
["farm_plant_pepper"]=true,
["farm_plant_pomegranate"]=true,
["farm_plant_potato"]=true,
["farm_plant_pumpkin"]=true,
["farm_plant_randomseed"]=true,
["farm_plant_tomato"]=true,
["farm_plant_watermelon"]=true,
["farm_plow"]=true,
--["farmrock"]=true,
--["farmrockflat"]=true,
--["Farmrocktall"]=true,
["fence"]=true,
--["fence_gate"]=true,
["firepit"]=true,
["firesuppressor"]=true,
["fish_box"]=true,
--["fissure"]=true,
--["fissure_grottowar"]=true,-- TODO
--["fissure_lower"]=true,
--["flies"]=true,
["flower"]=true,
["flower_cave"]=true,
["flower_cave_double"]=true,
["flower_cave_triple"]=true,
["flower_evil"]=true,
["flower_rose"]=true,
["flower_withered"]=true,
["fossil_stalker"]=true,
--["gargoyle_houndatk"]=true,
--["gargoyle_hounddeath"]=true,
--["gargoyle_werepigatk"]=true,
--["gargoyle_werepigdeath"]=true,
--["gargoyle_werepighowl"]=true,
["gingerbreadhouse"]=true,
["grass"]=true,
["gravestone"]=true,
["green_mushroom"]=true,
["grotto_moonglass_1"]=true,
["grotto_moonglass_3"]=true,
["grotto_moonglass_4"]=true,
["grotto_pool_big"]=true,
["grotto_pool_small"]=true,
--["grotto_waterfall_big"]=true,  - POI
["grotto_waterfall_small1"]=true,
["grotto_waterfall_small2"]=true,
["hedgehound_bush"]=true,
["hermithouse"]=true,
["hermithouse_construction1"]=true,
["hermithouse_construction2"]=true,
["hermithouse_construction3"]=true,
["homesign"]=true,
["hotspring"]=true,
["houndbone"]=true,
["houndmound"]=true,
["icebox"]=true,
["insanityrock"]=true,
--ivy_snar"]=true,
["klaus_sack"]=true,
["lava_pond"]=true,
["lava_pond_rock"]=true,
["lava_pond_rock2"]=true,
["lava_pond_rock3"]=true,
["lava_pond_rock4"]=true,
["lava_pond_rock5"]=true,
["lava_pond_rock6"]=true,
["lava_pond_rock7"]=true,
--["lavalight"]=true,
["lichen"]=true,
["lightflier_flower"]=true,
["lightning_rod"]=true,
["livingtree"]=true,
["lost_toy_1"]=true,
["lost_toy_10"]=true,
["lost_toy_11"]=true,
["lost_toy_14"]=true,
["lost_toy_18"]=true,
["lost_toy_19"]=true,
["lost_toy_2"]=true,
["lost_toy_42"]=true,
["lost_toy_43"]=true,
["lost_toy_7"]=true,
["lumpy_sapling"]=true,
["lunar_forge"]=true,
["lunarrift_crystal_big"]=true,
["lunarrift_crystal_small"]=true,
["lunarrift_portal"]=true,
["lunarthrall_plant"]=true,
["lureplant"]=true,
["madscience_lab"]=true,
["magician_chest"]=true,
["mandrake_planted"]=true,
["marblebean_sapling"]=true,
["marblepillar"]=true,
["marbleshrub"]=true,
["marbletree"]=true,
["marsh_bush"]=true,
--["marsh_plant"]=true,
["marsh_tree"]=true,
["mast"]=true,
["mast_malbatross"]=true,
["mastupgrade_lamp"]=true,
["mastupgrade_lightningrod"]=true,
["meatrack"]=true,
["meatrack_hermit"]=true,
["mermhead"]=true,
["mermhouse"]=true,
["mermking"]=true,
["mermthrone"]=true,
["mermwatchtower"]=true,
["mighty_gym"]=true,
["minisign"]=true,
["minotaurchest"]=true,
["molebathill"]=true,
["molehill"]=true,
["monkeybarrel"]=true,
["monkeyhut"]=true,
["monkeyisland_portal"]=true,
["monkeyisland_portal_debris"]=true,
["monkeypillar"]=true,
["monkeyqueen"]=true,
["monkeytail"]=true,
["moon_altar"]=true,
["moon_altar_astral"]=true,
["moon_altar_cosmic"]=true,
["moon_altar_link"]=true,
["moon_altar_rock_glass"]=true,
["moon_altar_rock_idol"]=true,
["moon_altar_rock_seed"]=true,
["moon_device"]=true,
["moon_fissure"]=true,
["moon_tree_tall"]=true,
["moonbase"]=true,
["moonbutterfly_sapling"]=true,
["moondial"]=true,
["moonglass_rock"]=true,
--["moonglass_stalactite1"]=true,
["moonglass_wobster_den"]=true,
["moonrock_pieces"]=true,
["moonspiderden"]=true,
["moonstorm_glass"]=true,
["moonstorm_static"]=true,
--["moose_nesting_ground"]=true, -- POI
["mooseegg"]=true,
["mound"]=true,
["multiplayer_portal"]=true,
["multiplayer_portal_moonrock"]=true,
["mushroom_farm"]=true,
["mushroom_light"]=true,
["mushroomsprout"]=true,
["mushroomsprout_dark"]=true,
["mushtree_tall"]=true,
["mushtree_medium"]=true,
["mushtree_small"]=true,
["mushtree_moon"]=true,
["nightlight"]=true,
["nightmaregrowth"]=true,
["nightmarelight"]=true,
["oasis_cactus"]=true,
["oasislake"]=true,
["ocean_trawler"]=true,
["oceantree_tall"]=true,
["oceanvine"]=true,
["oceanvine_cocoon"]=true,
["palmcone_sapling"]=true,
["palmconetree_tall"]=true,
["pandoraschest"]=true,
--["penguin_ice"]=true,
--["perdshrine"]=true,
["pighead"]=true,
["pighouse"]=true,
["pigking"]=true,
--["pigshrine"]=true,
["pigtorch"]=true,
--["pillar_algae"]=true,
--["pillar_atrium"]=true,
--["pillar_cave"]=true,
--["pillar_cave_flintless"]=true,
--["pillar_cave_rock"]=true, -- DONT NEED?
--["pillar_ruins"]=true,
--["pillar_stalactite"]=true,  -- DONT NEED
["pinecone_sapling"]=true,
["pirate_flag_pole"]=true,
["pirate_stash"]=true,
["pond"]=true,
--["pond_algae"]=true,
["pond_cave"]=true,
["pond_mos"]=true,
["portableblender"]=true,
["portablecookpot"]=true,
["portablespicer"]=true,
["portabletent"]=true,
["pottedfern"]=true,
["rabbithole"]=true,
["rabbithouse"]=true,
["rainometer"]=true,
["red_mushroom"]=true,
["reeds"]=true,
["researchlab"]=true,
["researchlab2"]=true,
["researchlab3"]=true,
["researchlab4"]=true,
["resurrectionstatue"]=true,
["resurrectionstone"]=true,
["rock_avocado_bush"]=true,
["rock_avocado_fruit_sprout_sapling"]=true,
["rock_flintless"]=true,
["rock_ice"]=true,
["rock_light"]=true,
["rock_moon"]=true,
["rock_moon_shell"]=true,
["rock_petrified_tree"]=true,
["rock1"]=true,
["rubble"]=true,
["ruins_bowl"]=true,
["ruins_cavein_obstacle"]=true,
["ruins_chair"]=true,
["ruins_chipbowl"]=true,
["ruins_plate"]=true,
["ruins_rubble_chair"]=true,
["ruins_rubble_table"]=true,
["ruins_rubble_vase"]=true,
["ruins_statue_head"]=true,
["ruins_statue_head_nogem"]=true,
["ruins_statue_mage"]=true,
["ruins_statue_mage_nogem"]=true,
["ruins_table"]=true,
["ruins_vase"]=true,
["ruinsrelic_bowl"]=true,
["ruinsrelic_chair"]=true,
["ruinsrelic_chipbowl"]=true,
["ruinsrelic_plate"]=true,
["ruinsrelic_table"]=true,
["ruinsrelic_vase"]=true,
["sacred_chest"]=true,
["saladfurnace"]=true,
["saltbox"]=true,
["saltlick"]=true,
["saltstack"]=true,
["sandblock"]=true,
["sanityrock"]=true,
["sapling"]=true,
["sapling_moon"]=true,
["scarecrow"]=true,
["scorched_skeleton"]=true,
["sculptingtable"]=true,
["sculpture_bishop"]=true,
["sculpture_knight"]=true,
["sculpture_rook"]=true,
["seastack"]=true,
["sentryward"]=true,
["sewing_mannequin"]=true,
--["shadow_pillar"]=true,
--["shadow_trap"]=true,
["shadowmeteor"]=true,
["shadowtentacle"]=true,
["siestahut"]=true,
["sisturn"]=true,
["skeleton"]=true,
["slurtlehole"]=true,
["spiderden"]=true,
["spiderhole"]=true,
["spiderhole_rock"]=true,
["stafflight"]=true,
["stalagmite"]=true,
["statue_marble"]=true,
["statue_marble_muse"]=true,
["statue_marble_pawn"]=true,
["statueglommer"]=true,
["statueharp"]=true,
["statuemaxwell"]=true,
["steeringwheel"]=true,
["succulent_plant"]=true,
["succulent_potted"]=true,
["table_winters_feast"]=true,
["tacklestation"]=true,
["tallbirdnest"]=true,
["telebase"]=true,
["teleportato_base"]=true,
["tent"]=true,
["tentacle"]=true,
["tentacle_pillar"]=true,
["tentacle_pillar_arm"]=true,
["tentacle_pillar_hole"]=true,
["terrariumchest"]=true,
["toadstool_cap"]=true,
--["tophat_container"]=true,
["townportal"]=true,
["trap_starfish"]=true,
--["trap_teeth_maxwell"]=true,
["treasurechest"]=true,
--["trinket_1_proj"]=true,
["trophyscale_fish"]=true,
["trophyscale_oversizedveggies"]=true,
["turfcraftingstation"]=true,
["twiggy_tall"]=true, -- ["twiggytree_tall"]=true,
--["underwater_salvageable"]=true,
["wall_hay"]=true,
["wall_moonrock"]=true,
["wall_ruins"]=true,
--["wall_ruins_2"]=true,
["wall_stone"]=true,
--["wall_stone_2"]=true,
["wall_wood"]=true,
["walrus_camp"]=true,
["wardrobe"]=true,
--["wargshrine"]=true,
["wasphive"]=true,
["waterplant"]=true,
["waterpump"]=true,
["watertree_pillar"]=true,
["watertree_root"]=true,
["weed_firenettle"]=true,
["weed_forgetmelots"]=true,
["weed_ivy"]=true,
["weed_tillweed"]=true,
["winch"]=true,
["winona_battery_low"]=true,
["winona_battery_high"]=true,
["winona_catapult"]=true,
["winona_spotlight"]=true,
["winterometer"]=true,
["wintersfeastoven"]=true,
["wobster_den"]=true,
["wormhole"]=true,
["wormlight_plant"]=true,
["worm"] = true,
["tumbleweed"] = true,
["bearger"]=true,
["warg"] = true,
["oceanfish_small_1"] = true,
["oceanfish_small_2"] = true,
["oceanfish_small_3"] = true,
["oceanfish_small_4"] = true,
["oceanfish_small_5"] = true,
["oceanfish_small_6"] = true,
["oceanfish_small_7"] = true,
["oceanfish_small_8"] = true,
["oceanfish_small_9"] = true,
["oceanfish_medium_1"] = true,
["oceanfish_medium_2"] = true,
["oceanfish_medium_3"] = true,
["oceanfish_medium_4"] = true,
["oceanfish_medium_5"] = true,
["oceanfish_medium_6"] = true,
["oceanfish_medium_7"] = true,
["oceanfish_medium_8"] = true,
["oceanfish_medium_9"] = true,

}



return PREFABS